name: modelExperimient

on:
  push:
      branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: /
    steps:
     -  run: echo Hello with CI/CD  
     -
        name: Checkout
        uses: actions/checkout@v2
     - 
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
     - 
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
     - 
        name: Test with pytest
        run: |
          cd CorrectAccent/
          
